{
 "title": "Crypto Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "100ms",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BTCUSD Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  instrument AS metric,\n  avg(price) AS \"price\"\nFROM crypto_trades\nWHERE\n  $__timeFilter(ts) AND\n  instrument = 'BTCUSD'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "BTCUSD Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  instrument AS metric,\n  sum(trade_size) - lag(sum(trade_size)) OVER (PARTITION BY instrument ORDER BY $__timeGroup(ts,$__interval)) AS \"trade_size\"\nFROM crypto_trades\nWHERE\n  $__timeFilter(ts) AND\n  instrument = 'BTCUSD'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "ETHUSD Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  instrument AS metric,\n  avg(price) AS \"price\"\nFROM crypto_trades\nWHERE\n  $__timeFilter(ts) AND\n  instrument = 'ETHUSD'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "ETHUSD Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  instrument AS metric,\n  sum(trade_size) - lag(sum(trade_size)) OVER (PARTITION BY instrument ORDER BY $__timeGroup(ts,$__interval)) AS \"trade_size\"\nFROM crypto_trades\nWHERE\n  $__timeFilter(ts) AND\n  instrument = 'ETHUSD'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "LTCUSD Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  instrument AS metric,\n  avg(price) AS \"price\"\nFROM crypto_trades\nWHERE\n  $__timeFilter(ts) AND\n  instrument = 'LTCUSD'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "LTCUSD Volume",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(ts,$__interval),\n  instrument AS metric,\n  sum(trade_size) - lag(sum(trade_size)) OVER (PARTITION BY instrument ORDER BY $__timeGroup(ts,$__interval)) AS \"trade_size\"\nFROM crypto_trades\nWHERE\n  $__timeFilter(ts) AND\n  instrument = 'LTCUSD'\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}