apiVersion: 1

datasources:
  - name: TimeSeriesDB
    type: postgres
    is_default: true
    url: host.docker.internal:5432
    database: $DBNAME
    user: $DBUSER
    org_id: 1
    editable: true
    jsonData:
      sslmode: 'disable'    
      timeInterval: 100ms
      postgresVersion: 1200
      timescaledb: true
    secureJsonData:
      password: $DBPASS
