version: "3.9"
services:
  timescaledb:
    build: ./timescaledb
    container_name: timescaledb
    restart: always
    env_file:
      - secrets/timescaledb.env
    volumes:
      - market-data:/var/lib/postgresql/data
    extra_hosts:
      - host.docker.internal:172.17.0.1
    ports:
      - 5432:5432
  grafana:
    container_name: grafana
    build: ./grafana
    restart: always
    depends_on:
      - timescaledb
    env_file:
      - secrets/grafana.env
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    extra_hosts:
      - host.docker.internal:172.17.0.1
    ports:
      - 3000:3000
  alpaca-client:
    container_name: alpaca-client
    build: ./alpaca_client
    restart: always
    depends_on:
      - timescaledb
    env_file:
      - secrets/alpaca.env
    entrypoint: "poetry run python /app/main.py start_crypto_client"
    extra_hosts:
      - host.docker.internal:172.17.0.1

volumes:
  market-data:
